const CREATE_POST_TEXT = "CREATE_POST_TEXT";
const CREATE_POST_EMOJI = "CREATE_POST_EMOJI";
const CREATE_POST_MEDIA = "CREATE_POST_MEDIA";
const CREATE_POST_CLEAR = "CREATE_POST_CLEAR";

export { CREATE_POST_TEXT, CREATE_POST_EMOJI, CREATE_POST_MEDIA, CREATE_POST_CLEAR };